# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Use 'jk' to escape in vi-mode
bindkey -M viins 'jk' vi-cmd-mode

# Keep your system specific configuration here
[ -f "$HOME/.zshrc-local" ] && source "$HOME/.zshrc-local"

# Environment variables {{{
export TERM="xterm-256color"
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export RIPGREP_CONFIG_PATH="$HOME/.ripgreprc"
export FZF_DEFAULT_COMMAND='rg --files --hidden'

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=8"
ZSH_AUTOSUGGEST_USE_ASYNC="true"
# Env variables }}}

# Aliases {{{
# Easy access to config
alias zshconfig="$EDITOR ~/.zshrc"
alias vimconfig="$EDITOR ~/.config/nvim/init.vim"

alias v="nvim"

alias tmux="tmux -2"
alias tsw="tmux switchc -t"
alias tl='tmux list-sessions'
alias trw="tmux renamew -t"
alias td="tmux detach-client"
alias ta='tmux attach -t'
alias ts='tmux new-session -s'

alias g="git"
alias ga='git add'
alias gc='git commit -v'
alias gd='git diff'
alias gds="git diff --staged"
alias glog='git log --oneline --decorate --graph'
alias gs='git status'
alias gp='git push'

alias ls='exa'
# Aliases }}}

# Custom Commands {{{
export function timer() {
  (\
    sleep $1 &&\
    terminal-notifier -title 'Timer' \
      -message "${2:-Timer has been completed}" \
      -sound default \
      -ignoreDnD\
  )&
}
# Custom Commands }}}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Use OSX true colours
unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1

eval "$(starship init zsh)"
